name: Build Scanbot Capacitor Example

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (Your Repo)
        uses: actions/checkout@v4

      - name: Clone Scanbot Capacitor Example
        run: |
          rm -rf project
          git clone https://github.com/doo/scanbot-barcode-scanner-sdk-example-capacitor-ionic.git project
          cd project
          ls -la

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Dependencies
        working-directory: project
        run: npm install

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Build Web (Ionic)
        working-directory: project
        run: ionic build

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Capacitor Sync Android
        working-directory: project
        run: npx cap sync android

      - name: Build Android Debug APK
        working-directory: project/android
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: scanbot-debug-apk
          path: project/android/app/build/outputs/apk/debug/app-debug.apk
